apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-with-parameters
spec:
  params:
    - name: flags
      type: string
      default: a
    - name: someURL
      type: string
      default: www.google.com
  steps:
    - name: build
      image: my-builder
      args: ["build", "$(params.flags)", "url=$(params.someURL)"]
